version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./fotrs_DB_03072023.sql:/dump.sql
      - ./restore_DB.sh:/docker-entrypoint-initdb.d/restore_DB.sh
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - MAXOPENCONNS=25
      - MAXIDLECONNS=25
      - MAXCONNLIFETIME=10 #in minutes
    depends_on:
      - db
